version: '2'

tasks:

    default:
        desc: builds
        deps: [build]

    clean:
        desc: cleans
        cmds:
            - go clean ./...

    upgrade:
        desc: upgrades
        cmds:
            - go get -u

    fmt:
        desc: formats
        cmds:
            - go fmt ./...
        sources:
            - '**/*.go'

    test:
        desc: tests
        cmds:
            - go test ./...
        deps: [fmt]
        sources:
            - '**/*.go'
            - 'test/**'

    race:
        desc: tests for race conditions
        cmds:
            - go test -race ./...
        deps: [fmt]
        sources:
            - '**/*.go'
            - 'test/**'

    cover:
        desc: checks coverage
        cmds:
            - go test -cover -covermode=atomic ./...
        deps: [fmt]
        sources:
            - '**/*.go'
            - 'test/**'

    build:
        desc: builds
        cmds:
            - go build ./cmd/bm
        deps: [fmt]
        sources:
            - '**/*.go'
        generates:
            - bm

    install:
        desc: installs
        cmds:
            - mkdir -p ~/.local/bin
            - cp bm ~/.local/bin/bm
        deps: [build]
