version: '2'

tasks:

    default:
        desc: builds
        deps: [build]

    clean:
        desc: cleans
        cmds:
            - vgo clean ./...

    upgrade:
        desc: upgrades
        cmds:
            - vgo get -u

    fmt:
        desc: formats
        cmds:
            - vgo fmt ./...
        sources:
            - '**/*.go'

    test:
        desc: tests
        cmds:
            - vgo test ./...
        deps: [fmt]
        sources:
            - '**/*.go'
            - 'test/**'

    race:
        desc: tests for race conditions
        cmds:
            - vgo test -race ./...
        env:
            CC: gcc
        deps: [fmt]
        sources:
            - '**/*.go'
            - 'test/**'

    cover:
        desc: checks coverage
        cmds:
            - vgo test -cover -covermode=atomic ./...
        deps: [fmt]
        sources:
            - '**/*.go'
            - 'test/**'

    build:
        desc: builds
        cmds:
            - vgo build ./cmd/bm
        deps: [fmt]
        sources:
            - '**/*.go'
        generates:
            - bm

    install:
        desc: installs
        cmds:
            - vgo install ./cmd/bm
        deps: [build]