version: 2
jobs:
    build:
        docker:
            - image: circleci/golang:1.11
        steps:
            - checkout
            - run: go test -v -race -covermode=atomic -coverprofile=coverage.out
