version: 2
jobs:
    build:
        docker:
            - image: circleci/golang:1.11
        working_directory: /go/src/github.com/grzegorz-zur/bare-minimum
        steps:
            - run: go get github.com/schrej/godacov 
            - checkout
            - run: go test -v -race -covermode=atomic -coverprofile=coverage.out
            - run: godacov -t $CODACY_TOKEN -r ./coverage.out -c $CIRCLE_SHA1
            - run: bash <(curl -s https://codecov.io/bash)